BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS users (
    user_id int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1),
    username varchar(8) NOT NULL UNIQUE,
    password varchar(32) NOT NULL
);
END TRANSACTION;